summary = """Software engineer with expertise in C++ and Qt across Automotive and Fintech.
Hands-on practitioner of Rust, Linux, and systems programming, with extensive homelab experience in networking and infrastructure.
Driven to build efficient systems and tackle complex challenges in a collaborative environment.
"""
interests = [
  "Designing and administering secure, segmented homelab environments.",
  "Optimizing Linux workflows through desktop environment customization and scripting.",
  "Designing PCBs and developing low-level firmware for embedded devices.",
]

[contact_info]
fullname = "Luu Hoang Kien"
title = "Software Developer"
email = "kien.luuhoang.arch@outlook.com"
github = "lulkien"
linkedin = "kienlh-dev"
phone = "+84988449631"
location = "Hanoi, Vietnam"

[[education]]
institution = "University of Engineering and Technology"
degree = "Bachelor degree"
area_of_study = "Electronic and Telecommunication"
date_range = "Sep 2016 - Oct 2020"

[[experience]]
company = "Rikkei Soft"
position = "C++ Developer"
date_range = "Oct 2024 - Present"

[[experience]]
company = "FPT Software"
position = "C++ Developer"
date_range = "Dec 2020 - Jun 2024"

[[skills]]
name = "Programming Languages"
description = "C++ (4+ years, Automotive & Fintech), Rust (Hobbyist, Open-Source)"

[[skills]]
name = "Frameworks & Libraries"
description = "Qt Framework (4+ years, Automotive)"

[[skills]]
name = "Systems & Administration"
description = "GNU/Linux, Shell Scripting"

[[skills]]
name = "Networking & Infrastructure"
description = "VLANs, Firewall, Network Segmentation, VPNs, Proxmox"

[[projects]]
name = "Enterprise Portfolio Accounting"
date_range = "Oct 2024 - Present"
description = "Engineered and maintained a high-performance, mission-critical accounting system for a multi-billion dollar global asset management firm."
highlights = [
  "Develop and maintain the core accounting system for a global asset management portfolio.",
  "Implement critical code changes to meet strict financial compliance and business requirements.",
  "Ensure system reliability and data integrity through proactive monitoring and troubleshooting.",
]

[[projects]]
name = "SNaviBox"
date_range = "May 2024 - Jun 2024"
description = "Enhanced and maintained the navigation platform for a major Japanese automotive client, utilizing C++."
highlights = [
  "Utilize expertise in automotive software and customer-specific requirements.",
  "Collaborate with cross-functional teams to implement new features and improvements.",
]

[[projects]]
name = "POIP.Cluster"
date_range = "Jan 2024 - Mar 2024"
description = "Developed and implemented the graphical user interface (GUI) for a next-generation digital instrument vehicle cluster."
highlights = [
  "Developed the Charging Manager front-end, creating key driver information displays.",
  "Ensured compliance with automotive performance standards in a resource-constrained embedded system.",
]

[[projects]]
name = "Cockpit2024"
date_range = "Jul 2023 - Dec 2023"
description = "Developed core applications for a next-generation automotive cockpit system, including the Navigation and Media Player modules from concept to demonstration."
highlights = [
  "Engineered the Navigation and Media Player applications for a production-ready infotainment platform.",
  "Integrated a text-to-speech (TTS) engine to deliver critical audio alerts and features.",
  "Automated build and release pipelines using shell scripting to accelerate development.",
  "Configured and optimized the underlying Linux OS for system stability and performance.",
]

[[projects]]
name = "Gen5.Premium"
date_range = "Dec 2020 - Jun 2023"
description = "Maintained and enhanced HMI layer for high-end automotive AVN systems, focusing on UX and feature development."
highlights = [
  "Owned development and maintenance of core Home Screen application",
  "Revamped Settings search functionality, improving usability and performance",
  "Resolved complex issues across the HMI platform through expert troubleshooting",
]

[[projects]]
name = "Sonant"
date_range = "Personal Project"
source_code = "https://github.com/lulkien/sonant"
description = "Lightweight C++ library that captures audio via the ALSA API and transcribes it in real-time using the Whisper.cpp."

[[projects]]
name = "Rusty Web Resume"
date_range = "Personal Project"
source_code = "https://github.com/lulkien/Rusty-Web-Resume"
demo = "https://resume.lulkien.com"
description = "Single-page web application resume using Rust and the Yew framework."

[[languages]]
name = "Vietnamese"
description = "Native"

[[languages]]
name = "English"
description = "General Proficiency"
